### ISSUE TITLE
Property 'AwesomeMarkers' does not exist on type 'typeof "....../node_modules/@types/leaflet/index"'.

### ISSUE THREAD

**Issue by rguntha** [sigma-geosistemas/Leaflet.awesome-markers#14]
Hi,
I am using 
Ionic 3.0
leaflet@1.3.3
leaflet.awesome-markers@2.0.4
@types/leaflet@1.2.9
@types/leaflet.awesome-markers@2.0.23

When I use ionic serve, I get the above error. But when I make any change to the code and it auto builds the changes and the issue is gone. But it always occurrs when I first run the ionic serve command.

**Comment by AlexGreg** [comment]
I think is related to the @type library and not this one, based on the error

closing for now
