### ISSUE TITLE
Help maintaining?

### ISSUE THREAD

**Issue by george-silva** [sigma-geosistemas/Leaflet.awesome-markers#15]
Folks, good afternoon!

I got the ownership of this package for the same reasons, a few yeas ago. There were bugfixes and evolutions that the original creator was not being able to make them.

So I contacted Github and inherit it.

This was a time when I:

1. Had a team of developers working with me
2. Had a company that used several packages like this one on a daily basis

So it was easier to maintain. Today I have none of these things and time to contribute to open-source is getting scarce.

Does anyone want to take ownership of the package ?

**Comment by george-silva** [comment]
@AlexGreg I'll transfer the repo to ya!

**Comment by george-silva** [comment]
Done. Let me know if you need further permissions on npm or whatever!

**Comment by AlexGreg** [comment]
errata..on npm is alexgreg

**Comment by AlexGreg** [comment]
Sure, no problem

**Comment by AlexGreg** [comment]
bump @george-silva

**Comment by AlexGreg** [comment]
@george-silva ?

**Comment by george-silva** [comment]
@AlexGreg added you as a maintainer.

**Comment by AlexGreg** [comment]
Excellent.. tomorrow or asap I'll release the new version which includes the correction on the package.json

**Comment by george-silva** [comment]
Cool. I appreciate it.

Took me a while, my trip was busy, só sorry for that delay

Em ter, 4 de dez de 2018 20:37, AlexGreg <notifications@github.com escreveu:
