### ISSUE TITLE
Error: Cannot find module "leaflet.awesome-markers" in Ionic3

### ISSUE THREAD

**Issue by JeongJun-Lee** [sigma-geosistemas/Leaflet.awesome-markers#16]
After installing by npm, I imported the module with leaflet in Ionic 3 like below.

import 'leaflet';
import 'leaflet.awesome-markers';

This emits error "Can not find module" like title.
Do you have any idea?

**Comment by AlexGreg** [comment]
related to #11 we just need to publish a new version to npm

@george-silva
