### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by mlazowik** [sigma-geosistemas/Leaflet.awesome-markers#4]
Do you think you could [publish](https://docs.npmjs.com/getting-started/publishing-npm-packages) this package to [npm registry](https://www.npmjs.com)? Unfortunately it looks like it would like a bit of overhead with each release, but not that much.

Thanks for keeping this plugin alive!

**Comment by george-silva** [comment]
@mlazowik sure.

**Comment by george-silva** [comment]
https://www.npmjs.com/package/leaflet.awesome-markers

published. I don't have much experience here, but if you are using webpack, I guess you'll have to map this.

let me know if this works.

**Comment by mlazowik** [comment]
The package does work, thanks!

I see some issues though:
 * the version on npm is now 1.0.0, which does not match neither the latest GitHub release nor the bower release. I think all these should be in sync.
 * the actual published code is current master, which is not a release at all. This is probably because you needed `package.json`, right? Either way master has broken markers on high dpi screens since 2d9a528. I'm going to make a pull req to fix that now.
 * `main` in `package.json` points to non existing file, but webpack still handles importing js somehow, I'm not sure what is going on there.

**Comment by george-silva** [comment]
@mlazowik about versions:

1. I've matched the version on npm;
2. Will publish the new version to bower as well;
3. No idea about that as well;

**Comment by mlazowik** [comment]
Great, thanks!
